server:
  port: 8080
spring:
  application:
    name: gateway_demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    name: test_demo
    username: root
    password: password
  flyway:
    enabled: true
  cloud:
    gateway:
      enabled: true
      routes:
        - id: main_application_demo
          uri: http://localhost:8081
          order: 1
          predicates:
            - Path=/main_application_demo/**
          filters:
            - Auth=true